### ISSUE TITLE
ErrorException: session_name(): Cannot change session name when headers already sent

### ISSUE THREAD

**Issue by RossIV** [RoboJackets/apiary#397]
Figure out why this is happening and make it stop.
```
[2018-07-12 17:54:48] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: session_name(): Cannot change session name when headers already sent in /var/www/apiary/production/vendor/subfission/cas/src/Subfission/Cas/CasManager.php:38
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'session_name():...', '/var/www/apiary...', 38, Array)
#1 /var/www/apiary/production/vendor/subfission/cas/src/Subfission/Cas/CasManager.php(38): session_name('session')
#2 /var/www/apiary/production/vendor/subfission/cas/src/Subfission/Cas/CasServiceProvider.php(35): Subfission\Cas\CasManager->__construct(Array)
#3 /var/www/apiary/production/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Subfission\Cas\CasServiceProvider->Subfission\Cas\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 /var/www/apiary/production/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#5 /var/www/apiary/production/vendor/laravel/framework/src/ in /var/www/apiary/production/vendor/subfission/cas/src/Subfission/Cas/CasManager.php:38
Stack trace:
#0 {main}
```

**Comment by kberzinch** [comment]
This is subfission/cas#59

**Comment by kberzinch** [comment]
This is likely fixed upstream now: https://github.com/apereo/phpCAS/issues/255
